import 'package:flutter/material.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms of Service'),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 800),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Terms of Service',
                  style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Last updated: November 29, 2025',
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.6),
                      ),
                ),
                const SizedBox(height: 32),
                _buildSection(
                  context,
                  '1. Acceptance of Terms',
                  '''Welcome to PlotEngine. By accessing or using our creative writing application and services ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.

These Terms constitute a legally binding agreement between you and PlotEngine. Please read them carefully.''',
                ),
                _buildSection(
                  context,
                  '2. Description of Service',
                  '''PlotEngine is an AI-powered creative writing application that provides:

• A rich text editor for writing and organizing stories
• Cloud storage for your writing projects
• AI-assisted features including entity recognition, consistency checking, and writing suggestions
• Knowledge base management for tracking story elements (characters, locations, objects, events)
• Multi-platform access via web and desktop applications

The Service may be updated, modified, or discontinued at any time without prior notice.''',
                ),
                _buildSection(
                  context,
                  '3. Account Registration',
                  '''To use PlotEngine, you must:

• Create an account using Google Sign-In or other supported authentication methods
• Provide accurate and complete information
• Be at least 13 years of age (or the minimum age in your jurisdiction)
• Maintain the security of your account credentials
• Notify us immediately of any unauthorized access

You are responsible for all activities that occur under your account.''',
                ),
                _buildSection(
                  context,
                  '4. User Content and Intellectual Property',
                  '''Your Content: You retain full ownership of all creative content you create using PlotEngine, including but not limited to stories, characters, plots, and worldbuilding elements ("User Content").

License to PlotEngine: By using our Service, you grant PlotEngine a limited, non-exclusive license to:
• Store, process, and display your User Content to provide the Service
• Process your content through AI features you enable
• Create backups for data protection purposes

This license terminates when you delete your content or account.

Our Content: PlotEngine and its original content, features, and functionality are owned by PlotEngine and are protected by international copyright, trademark, and other intellectual property laws.

AI-Generated Content: Any suggestions, improvements, or content generated by our AI features based on your input are provided as tools for your creative process. You retain ownership of works you create using these suggestions.''',
                ),
                _buildSection(
                  context,
                  '5. Acceptable Use',
                  '''You agree NOT to use PlotEngine to:

• Create, store, or distribute content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable
• Infringe upon intellectual property rights of others
• Attempt to gain unauthorized access to our systems or other users' accounts
• Interfere with or disrupt the Service or servers
• Use automated means to access the Service without permission
• Reverse engineer or attempt to extract source code
• Use the Service for any commercial purpose without authorization
• Violate any applicable laws or regulations

We reserve the right to suspend or terminate accounts that violate these terms.''',
                ),
                _buildSection(
                  context,
                  '6. AI Features and Limitations',
                  '''PlotEngine uses artificial intelligence to provide writing assistance:

Accuracy: AI-generated suggestions, entity recognition, and consistency checks are provided as creative tools. They may not always be accurate or appropriate for your needs. You are responsible for reviewing and editing all AI suggestions.

Content Processing: When you use AI features, your content is processed by third-party AI providers. This processing is subject to their terms of service and privacy policies.

No Guarantee: We do not guarantee that AI features will identify all inconsistencies, recognize all entities, or provide perfect suggestions. Use your judgment as the author.

Fair Use: AI features consume computational resources. Excessive or abusive use may result in temporary limitations on your account.''',
                ),
                _buildSection(
                  context,
                  '7. Credits and Billing',
                  '''Credit System: Some AI features require credits. Credits are consumed when you use these features.

Purchases: Credits may be purchased through the Service. All purchases are final and non-refundable except as required by law.

Free Tier: We may offer free credits or features. These may be modified or discontinued at any time.

Pricing Changes: We reserve the right to modify pricing with reasonable notice to users.''',
                ),
                _buildSection(
                  context,
                  '8. Data and Privacy',
                  '''Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.

By using the Service, you consent to the collection, use, and sharing of your information as described in our Privacy Policy.''',
                ),
                _buildSection(
                  context,
                  '9. Disclaimer of Warranties',
                  '''THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.

We do not warrant that:
• The Service will be uninterrupted, secure, or error-free
• Results from the Service will be accurate or reliable
• Any errors will be corrected
• The Service will meet your specific requirements

You use the Service at your own risk. We recommend maintaining backups of important work.''',
                ),
                _buildSection(
                  context,
                  '10. Limitation of Liability',
                  '''TO THE MAXIMUM EXTENT PERMITTED BY LAW, PLOTENGINE SHALL NOT BE LIABLE FOR:

• Any indirect, incidental, special, consequential, or punitive damages
• Loss of profits, data, or goodwill
• Service interruption or data loss
• Any damages arising from your use of the Service

Our total liability shall not exceed the amount you paid to us in the twelve (12) months preceding the claim.''',
                ),
                _buildSection(
                  context,
                  '11. Indemnification',
                  '''You agree to indemnify and hold harmless PlotEngine, its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from:

• Your use of the Service
• Your User Content
• Your violation of these Terms
• Your violation of any third-party rights''',
                ),
                _buildSection(
                  context,
                  '12. Termination',
                  '''You may terminate your account at any time through the application settings.

We may suspend or terminate your access to the Service:
• For violation of these Terms
• For extended periods of inactivity
• If required by law
• At our sole discretion with reasonable notice

Upon termination, your right to use the Service ceases immediately. You may request export of your data before termination.''',
                ),
                _buildSection(
                  context,
                  '13. Changes to Terms',
                  '''We reserve the right to modify these Terms at any time. We will provide notice of material changes by:

• Posting the updated Terms on our website
• Sending an email notification
• Displaying a notice within the application

Continued use of the Service after changes constitutes acceptance of the modified Terms.''',
                ),
                _buildSection(
                  context,
                  '14. Governing Law',
                  '''These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which PlotEngine operates, without regard to conflict of law principles.

Any disputes arising from these Terms or the Service shall be resolved through binding arbitration or in the courts of competent jurisdiction.''',
                ),
                _buildSection(
                  context,
                  '15. General Provisions',
                  '''Entire Agreement: These Terms, together with our Privacy Policy, constitute the entire agreement between you and PlotEngine.

Severability: If any provision of these Terms is found invalid, the remaining provisions shall continue in effect.

Waiver: Our failure to enforce any right or provision shall not constitute a waiver of such right or provision.

Assignment: You may not assign or transfer these Terms. We may assign our rights and obligations without restriction.

Contact: For questions about these Terms, please contact us at support@plotengine.app.''',
                ),
                const SizedBox(height: 24),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.primaryContainer.withValues(alpha: 0.3),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.info_outline,
                        color: Theme.of(context).colorScheme.primary,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          'By using PlotEngine, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.',
                          style: Theme.of(context).textTheme.bodyMedium,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 48),
                Center(
                  child: Text(
                    '© 2025 PlotEngine. All rights reserved.',
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.5),
                        ),
                  ),
                ),
                const SizedBox(height: 24),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSection(BuildContext context, String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(
                  fontWeight: FontWeight.w600,
                ),
          ),
          const SizedBox(height: 12),
          Text(
            content,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  height: 1.6,
                ),
          ),
        ],
      ),
    );
  }
}
